### ISSUE TITLE
Help with Ping360 order of operations

### ISSUE THREAD

**Issue by caileighf** [bluerobotics/ping-protocol#184]
Hi There! 

I am having trouble getting data from the Ping360. When I run the example `ping360.py` I get the output pasted below. It hangs somewhere after the first print call like this: `print("full scan in %dms, %dHz" % (1000*(tend_s - tstart_s), 400/(tend_s - tstart_s)))`.

I'm also confused by the fields `_data(hex)` and `_data(string)`. I have been using the Ping1D which returns floating point numbers for the profile data (of course totally different sensor I don't expect the same data types). I checked the documentation for the data field: "'8 bit binary data array representing sonar echo strength'" but I'm not sure what that means. Do the byte values represent a complex number for angle and magnitude? If yes, how do I convert those byte values to a complex number? (I'm pretty new to sonar data so I apologize if these are "dumb questions"!) 

For order of operations, it would help to understand which methods will kick off a sample vs. methods that only set parameters. The example in `ping360.py` had a lot going on so I'm not sure what is happening with the hardware at any point. I am trying to set my hardware params then sample continuously while writing that data to a file. Is that possible to write a quick example for?

Thanks!

```
user:~/repos/venvs/_echo/lib/python3.6/site-packages/brping$ python3 ping360.py --device /dev/ttyUSB0 
Opening /dev/ttyUSB0 at 115200 bps
Initialized: True


--------------------------------------------------
ID: 2300 - device_data
Header: start_1: 66 start_2: 82 payload_length: 14 message_id: 2300 src_device_id: 2 dst_device_id: 0
Payload:
  - mode: 0
  - gain_setting: 0
  - angle: 64
  - transmit_duration: 32
  - sample_period: 80
  - transmit_frequency: 800
  - number_of_samples: 200
  - data_length: 0
  - data: []
Checksum: 835 check: 835 pass: True


--------------------------------------------------
ID: 2300 - device_data
Header: start_1: 66 start_2: 82 payload_length: 14 message_id: 2300 src_device_id: 2 dst_device_id: 0
Payload:
  - mode: 0
  - gain_setting: 0
  - angle: 64
  - transmit_duration: 32
  - sample_period: 80
  - transmit_frequency: 800
  - number_of_samples: 200
  - data_length: 0
  - data: []
Checksum: 835 check: 835 pass: True


--------------------------------------------------
ID: 2300 - device_data
Header: start_1: 66 start_2: 82 payload_length: 14 message_id: 2300 src_device_id: 2 dst_device_id: 0
Payload:
  - mode: 0
  - gain_setting: 0
  - angle: 64
  - transmit_duration: 32
  - sample_period: 80
  - transmit_frequency: 800
  - number_of_samples: 200
  - data_length: 0
  - data: []
Checksum: 835 check: 835 pass: True
---------------------------------------------------------
~Ping Object~
  - _angle: 399
  - _data(hex): ['0x43', '0x8b', '0xbf', '0xe4', '0xfc', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xff', '0xfb', '0xf9', '0xf8', '0xf9', '0xfc', '0xfc', '0xf9', '0xf6', '0xf2', '0xeb', '0xe8', '0xe8', '0xe4', '0xe0', '0xdc', '0xd2', '0xc7', '0xc1', '0xc0', '0xb8', '0xac', '0xb3', '0xbf', '0xc9', '0xd0', '0xd2', '0xcd', '0xc2', '0xbd', '0xbd', '0xc0', '0xc3', '0xc6', '0xc8', '0xc8', '0xc7', '0xc6', '0xc4', '0xbe', '0xb9', '0xb4', '0xb0', '0xb3', '0xb2', '0xb0', '0xa9', '0xa2', '0xa1', '0x9e', '0x99', '0x94', '0x98', '0x9d', '0xa1', '0xa6', '0xab', '0xa9', '0xa2', '0x9b', '0x8d', '0x85', '0x7c', '0x7a', '0x7b', '0x7c', '0x77', '0x76', '0x7e', '0x83', '0x85', '0x7f', '0x7b', '0x7c', '0x82', '0x86', '0x88', '0x8a', '0x8a', '0x89', '0x92', '0x9e', '0xa8', '0xae', '0xb4', '0xb8', '0xbb', '0xbb', '0xba', '0xb8', '0xb8', '0xb7', '0xb7', '0xb5', '0xb5', '0xb4', '0xb3', '0xb3', '0xb0', '0xa8', '0xa5', '0xa3', '0xa1', '0xa0', '0xa0', '0xa0', '0xa0', '0xa0', '0xa1', '0xa0', '0x9d', '0x95', '0x89', '0x7a', '0x73', '0x6e', '0x68', '0x64', '0x68', '0x71', '0x7a', '0x81', '0x86', '0x8a', '0x8e', '0x90', '0x8f', '0x8d', '0x87', '0x82', '0x7e', '0x7c', '0x7e', '0x7f', '0x7e', '0x7e', '0x7e', '0x7e', '0x7d', '0x7b', '0x78', '0x76', '0x71', '0x70', '0x6a', '0x65']
  - _data(string): b'C\x8b\xbf\xe4\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfb\xf9\xf8\xf9\xfc\xfc\xf9\xf6\xf2\xeb\xe8\xe8\xe4\xe0\xdc\xd2\xc7\xc1\xc0\xb8\xac\xb3\xbf\xc9\xd0\xd2\xcd\xc2\xbd\xbd\xc0\xc3\xc6\xc8\xc8\xc7\xc6\xc4\xbe\xb9\xb4\xb0\xb3\xb2\xb0\xa9\xa2\xa1\x9e\x99\x94\x98\x9d\xa1\xa6\xab\xa9\xa2\x9b\x8d\x85|z{|wv~\x83\x85\x7f{|\x82\x86\x88\x8a\x8a\x89\x92\x9e\xa8\xae\xb4\xb8\xbb\xbb\xba\xb8\xb8\xb7\xb7\xb5\xb5\xb4\xb3\xb3\xb0\xa8\xa5\xa3\xa1\xa0\xa0\xa0\xa0\xa0\xa1\xa0\x9d\x95\x89zsnhdhqz\x81\x86\x8a\x8e\x90\x8f\x8d\x87\x82~|~\x7f~~~~}{xvqpje'
  - _data_length: 200
  - _dst_device_id: 0
  - _gain_setting: 0
  - _mode: 0
  - _number_of_samples: 200
  - _reserved: 0
  - _sample_period: 80
  - _src_device_id: 2
  - _transmit_duration: 32
  - _transmit_frequency: 800
  - _version_major: 1
  - _version_minor: 0
  - _version_patch: 0
  - iodev(string): Serial<id=0x7f0ed0e2a978, open=True>(port='/dev/ttyUSB0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False)
  - my_id: 255
  - parser: <brping.pingmessage.PingParser object at 0x7f0ed0e2a828>
  - server_address: None
full scan in 18707ms, 21Hz
```
